sonar.organization=isw-commerce-group
sonar.projectKey=ISW-commerce-group_e-commerce-demo
sonar.projectName=e-commerce-demo
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info