sonar.organization=ISW-commerce-group
sonar.projectKey=isw-commerce-group-frontend
sonar.projectName=e-commerce-demo-frontend
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info